CLOwl_webapp/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClowlWebApp.Data;
using ClowlWebApp.Entities;

namespace ClowlWebApp.Controllers
{
    public class ContentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContentController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int categoryItemId)
        {
            Content content = await (from item in _context.Content
                                     where item.CategoryItem.Id == categoryItemId
                                     select new Content
                                     {
                                         Title = item.Title,
                                         VideoLink = item.VideoLink,
                                         HTMLContent = item.HTMLContent
                                     }).FirstOrDefaultAsync();

            var categoryId = await (from item in _context.CategoryItem
                                    where item.Id == categoryItemId
                                    select item.CategoryId).FirstOrDefaultAsync();

            List<CategoryItem> categoryItems = await (from item in _context.CategoryItem
                                                      where item.CategoryId == categoryId
                                                      select new CategoryItem
                                                      {
                                                          Id = item.Id,
                                                          Title = item.Title,
                                                          Description = item.Description,
                                                          DateTimeItemReleased = item.DateTimeItemReleased,
                                                          MediaTypeId = item.MediaTypeId,
                                                          CategoryId = categoryId
                                                      }).ToListAsync();

            ViewBag.categoryItems = categoryItems;
            return View(content);
        }
    }
}

CLOwl_webapp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ClowlWebApp.Data;
using ClowlWebApp.Entities;
using ClowlWebApp.Models;

namespace ClowlWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels = null;
            IEnumerable<GroupedCategoryItemsByCategoryModel> groupedCategoryItemsByCategoryModels = null;
            CategoryDetailsModel categoryDetailsModel = new CategoryDetailsModel();

            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);

                if (user != null)
                {
                    categoryItemDetailsModels = await GetCategoryItemDetails();
                    groupedCategoryItemsByCategoryModels = GetGroupedCategoryItemsByCategory(categoryItemDetailsModels);

                    categoryDetailsModel.GroupedCategoryItemsByCategoryModels = groupedCategoryItemsByCategoryModels;

                }

            }
            else
            {
                var categories = await GetCategoriesThatHaveContent();

                categoryDetailsModel.Categories = categories;

            }

            return View(categoryDetailsModel);
        }


        private async Task<List<Category>> GetCategoriesThatHaveContent()
        {
            var categoriesWithContent = await (from category in _context.Category
                                               join categoryItem in _context.CategoryItem
                                               on category.Id equals categoryItem.CategoryId
                                               join content in _context.Content
                                               on categoryItem.Id equals content.CategoryItem.Id
                                               select new Category
                                               {
                                                   Id = category.Id,
                                                   Title = category.Title,
                                                   Description = category.Description,
                                                   ThumbnailImagePath = category.ThumbnailImagePath
                                               }).Distinct().ToListAsync();
            return categoriesWithContent;

        }

        private IEnumerable<GroupedCategoryItemsByCategoryModel> GetGroupedCategoryItemsByCategory(IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels)
        {
            return from item in categoryItemDetailsModels
                   group item by item.CategoryId into g
                   select new GroupedCategoryItemsByCategoryModel
                   {
                       Id = g.Key,
                       Title = g.Select(c => c.CategoryTitle).FirstOrDefault(),
                       Items = g
                   };
        }

        private async Task<IEnumerable<CategoryItemDetailsModel>> GetCategoryItemDetails()
        {
            return await (from catItem in _context.CategoryItem
                          join category in _context.Category
                          on catItem.CategoryId equals category.Id
                          join content in _context.Content
                          on catItem.Id equals content.CategoryItem.Id
                          join mediaType in _context.MediaType
                          on catItem.MediaTypeId equals mediaType.Id
                          select new CategoryItemDetailsModel
                          {
                              CategoryId = category.Id,
                              CategoryTitle = category.Title,
                              CategoryItemId = catItem.Id,
                              CategoryItemTitle = catItem.Title,
                              CategoryItemDescription = catItem.Description,
                              MediaImagePath = mediaType.ThumbnailImagePath
                          }).ToListAsync();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CLOwl_webapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if (Model.GroupedCategoryItemsByCategoryModels != null)
{
    <div class="row">
        <div class="col-md-6">
            <h2>Your Courses</h2>
        </div>
    </div>

    @if (Model.GroupedCategoryItemsByCategoryModels != null)
    {
        <div class="row mt-3">
            <div class="col-md-12">

                @foreach (var cat in Model.GroupedCategoryItemsByCategoryModels)
                {
                    <div class="card mt-2">
                        <h4 class="card-header text-secondary bg-white" style="cursor:pointer" data-toggle="collapse" data-target="#collapse_@cat.Id" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            @cat.Title
                        </h4>
                        <div id="collapse_@cat.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            <hr />
                            @foreach (var item in cat.Items)
                            {
                                <div class="mt-2">
                                    <img src="@item.MediaImagePath" width="100" height="100" class="img-thumbnail float-left mr-2" />
                                    <h5 class="card-title mt-2">
                                        <a class="text-dark" asp-controller="Content" asp-action="Index" asp-route-CategoryItemId="@item.CategoryItemId">@item.CategoryItemTitle</a>
                                    </h5>
                                    <p class="card-text text-dark mt-2">
                                        @item.CategoryItemDescription
                                    </p>
                                </div>
                            }
                        </div>
                    </div>
                }

            </div>
        </div>
    }
    else
    {
        <h4 class="mt-2 text-warning">There are no courses available now</h4>

    }
}
else
{
    <partial name="_DefaultHomePageContentPartial" model="@Model.Categories" />
}


<div class="modal fade" id="UserLoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserLoginPartial" model="new LoginModel
        {
            Email = String.Empty,
            Password = String.Empty,
            RememberMe = false
        }">
</div>

<div class="modal fade" id="UserRegistrationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserRegistrationPartial" model="new RegistrationModel
        {
            Email = String.Empty,
            Password = String.Empty,
            ConfirmPassword = String.Empty,
            FirstName = String.Empty,
            LastName = String.Empty,
            PhoneNumber = String.Empty,
            Address1 = String.Empty,
            Address2 = String.Empty,
            PostCode = String.Empty,
            AcceptUserAgreement = false
        }">
</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_AuthScriptsPartial");
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }

}