CLOwl_webapp/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClowlWebApp.Data;
using ClowlWebApp.Entities;
using Microsoft.AspNetCore.Authorization;

namespace ClowlWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Creator")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        private async Task<IActionResult> StandardCRUDIndex(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return await StandardCRUDIndex(id);
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            return await StandardCRUDIndex(id);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            return await StandardCRUDIndex(id);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

CLOwl_webapp/Areas/Admin/Controllers/CreatorAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClowlWebApp.Data;
using ClowlWebApp.Entities;
using Microsoft.AspNetCore.Authorization;
using ClowlWebApp.Models;
using Microsoft.AspNetCore.Identity;

namespace ClowlWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CreatorAccountsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public CreatorAccountsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Admin/CreatorAccounts
        public async Task<IActionResult> Index()
        {
            List<UserRole> list = await (from userItem in _context.Users
                                         join userRoleItem in _context.UserRoles
                                         on userItem.Id equals userRoleItem.UserId
                                         into g1
                                         from userWithRole in g1.DefaultIfEmpty()
                                         join RoleItem in _context.Roles
                                         on userWithRole.RoleId equals RoleItem.Id
                                         into g2
                                         from fullTable in g2.DefaultIfEmpty()
                                         where fullTable.NormalizedName != "ADMIN"
                                         select new UserRole
                                         {
                                             UserName = userItem.UserName.ToString(),
                                             Role = fullTable.NormalizedName ?? null
                                         }).ToListAsync();

            ViewBag.UserList = list;
            return View();
        }

        [HttpPost]
        public async Task<bool> ChangeRole(UserRole userRole)
        {
            var user = await _userManager.FindByNameAsync(userRole.UserName);
            try
            {
                if (userRole.Role == "CREATOR")
                {
                    await _userManager.AddToRoleAsync(user, userRole.Role);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, "CREATOR");
                }
            }
            catch (Exception)
            {
                return false;
            }

            return true;
        }
    }
}

CLOwl_webapp/Areas/Admin/Controllers/MediaTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClowlWebApp.Data;
using ClowlWebApp.Entities;
using Microsoft.AspNetCore.Authorization;

namespace ClowlWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MediaTypeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MediaTypeController(ApplicationDbContext context)
        {
            _context = context;
        }

        private async Task<IActionResult> StandardCRUDIndex(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mediaType = await _context.MediaType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mediaType == null)
            {
                return NotFound();
            }

            return View(mediaType);
        }

        // GET: Admin/MediaType
        public async Task<IActionResult> Index()
        {
            return View(await _context.MediaType.ToListAsync());
        }

        // GET: Admin/MediaType/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return await StandardCRUDIndex(id);
        }

        // GET: Admin/MediaType/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/MediaType/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ThumbnailImagePath")] MediaType mediaType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mediaType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mediaType);
        }

        // GET: Admin/MediaType/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            return await StandardCRUDIndex(id);
        }

        // POST: Admin/MediaType/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ThumbnailImagePath")] MediaType mediaType)
        {
            if (id != mediaType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mediaType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MediaTypeExists(mediaType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mediaType);
        }

        // GET: Admin/MediaType/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            return await StandardCRUDIndex(id);
        }

        // POST: Admin/MediaType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mediaType = await _context.MediaType.FindAsync(id);
            _context.MediaType.Remove(mediaType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MediaTypeExists(int id)
        {
            return _context.MediaType.Any(e => e.Id == id);
        }
    }
}

CLOwl_webapp/Controllers/UserAuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClowlWebApp.Data;
using ClowlWebApp.Entities;
using ClowlWebApp.Models;

namespace ClowlWebApp.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;

        public UserAuthController(ApplicationDbContext context,
                                  UserManager<ApplicationUser> userManager,
                                  SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            loginModel.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.Email,
                                                                     loginModel.Password,
                                                                     loginModel.RememberMe,
                                                                     lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    loginModel.LoginInValid = "";
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt");
                }

            }
            return PartialView("_UserLoginPartial", loginModel);

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(RegistrationModel registrationModel)
        {
            registrationModel.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = registrationModel.Email,
                    Email = registrationModel.Email,
                    PhoneNumber = registrationModel.PhoneNumber,
                    FirstName = registrationModel.FirstName,
                    LastName = registrationModel.LastName,
                    Address1 = registrationModel.Address1,
                    Address2 = registrationModel.Address2,
                    PostCode = registrationModel.PostCode

                };

                var result = await _userManager.CreateAsync(user, registrationModel.Password);

                if (result.Succeeded)
                {
                    registrationModel.RegistrationInValid = "";

                    await _signInManager.SignInAsync(user, isPersistent: false);

                    return PartialView("_UserRegistrationPartial", registrationModel);
                }

                AddErrorsToModelState(result);

            }
            return PartialView("_UserRegistrationPartial", registrationModel);

        }

        // Walidacja po stronie klienta (przy pomocy UserRegistration.js)
        [AllowAnonymous]
        public async Task<bool> UserNameExists(string userName)
        {
            bool userNameExists = await _context.Users.AnyAsync(u => u.UserName.ToUpper() == userName.ToUpper());

            if (userNameExists)
                return true;

            return false;

        }

        private void AddErrorsToModelState(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }
    }
}

CLOwl_webapp/Views/Shared/_AuthScriptsPartial.cshtml
<script src="~/js/UserRegistration.js" asp-append-version="true"></script>
<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlerts.js" asp-append-version="true"></script>

CLOwl_webapp/Views/Shared/_DefaultHomePageContentPartial.cshtml
@model IEnumerable<Category>
<!--Hero Section-->
<div class="hero section">
    <img class="img-fluid" src="~/Images/HeroImage.jpeg">
    <div class="hero-heading">
        <h2 class="hero-heading-text">Learn Software Engineering at <strong>Clowl</strong></h2>
        <a id="HeroRegisterButton" class="btn btn-outline-info btn-lg text-light hero-register-button" data-toggle="modal" data-target="#UserRegistrationModal">Register</a>
    </div>
</div>

<hr class="section-divider" />

<!--Courses Section-->
<div id="Courses" class="courses section">
    <h3 class="section-header"><i class="fas fa-laptop-code mr-2 text-info"></i>Courses</h3>
    @{

        var catList = new List<Category>();
        catList = Model.ToList();

        <partial name="_DisplayCardRowPartial" model="catList" />

    }
</div>

<hr class="section-divider" />

<!--Contact Us Section-->

<div id="ContactUs" class="contact-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-phone-alt mr-2 text-info"></i>Contact Us</h3>
    <div class="col-md-5">
        Email us any questions or inquiries. We would be happy to answer your questions and set up a meeting with you.
    </div>
    <div class="mt-3">
        <div class="col-md-8">
            <form>
                <input type="hidden" />
                <div class="form-group">
                    <label for="Name" class="control-label">Name: </label>
                    <input id="Name" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email: </label>
                    <input id="Email" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Subject" class="control-label">Subject: </label>
                    <input id="Subject" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="MessageBody" class="control-label">Message: </label>
                    <textarea id="Messagebody" cols="30" rows="10" class="form-control"></textarea>

                </div>
                <div class="form-group d-flex">
                    <input type="button" value="Send Email" class="btn btn-outline-info ml-auto" />
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="section-divider" />

<!--About Us Section-->

<div id="AboutUs" class="about-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-chalkboard-teacher mr-2 text-info"></i>About Us</h3>
    <div class="mt-3 mb-5">
        <div class="col-md-5">
            <p>
                <strong>Clowl</strong> provides articles and courses on programming topics. We started in 2020 and continue to provide high quality Tech content to our members.
            </p>
        </div>
    </div>
</div>

CLOwl_webapp/Views/Shared/_DisplayCardRowPartial.cshtml
@model IEnumerable<Category>

@if (Model.Count() > 0)
{
    <div class="row mt-3">
        @foreach (Category item in Model)
        {
            <div class="col-md-3 mt-3">
                <a href="#" class="register-link text-dark" data-categoryId="@item.Id">
                    <div class="card">
                        <img class="img-thumbnail" src="@item.ThumbnailImagePath" alt="@item.Title">
                        <div class="card-body">
                            <h5 class="card-title">@item.Title</h5>
                            <p class="card-text">@item.Description</p>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
}

CLOwl_webapp/Views/Shared/_SidebarScriptsPartial.cshtml
<script src="~/js/Sidebar.js"></script>

CLOwl_webapp/Views/Shared/_UserLoginPartial.cshtml
@model ClowlWebApp.Models.LoginModel

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Login</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_login">
            </div>
            <form id="UserLoginForm" asp-controller="UserAuth" asp-action="Login">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="LoginInValid">
                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Email" placeholder="Email Address" class="form-control">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Password" placeholder="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group-row">
                    <div class="col-md-8 offset-md-4">
                        <div class="form-check">
                            <input asp-for="RememberMe" class="form-check-input">
                            <label asp-for="RememberMe" class="form-check-label"></label>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" id="login" name="login" class="btn btn-primary">Login</button>
        </div>
    </div>
</div>

CLOwl_webapp/Views/Shared/_UserMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using ClowlWebApp.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
    <li class="nav-item dropdown show">
        <a class="dropdown-toggle nav-link text-dark" href="#" data-toggle="dropdown"><i class="fas fa-screwdriver mr-2 text-info"></i>Admin</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index"><i class="fas fa-box mr-2 text-info"></i>Categories</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="MediaType" asp-action="Index"><i class="fas fa-file-video mr-2 text-info"></i>Media Types</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="CreatorAccounts" asp-action="Index"><i class="fa-solid fa-person mr-2 text-info"></i>Creator Accounts</a>
        </div>
    </li>
}

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "creator"))
{
    <li class="nav-item dropdown show">
        <a class="dropdown-toggle nav-link text-dark" href="#" data-toggle="dropdown"><i class="fas fa-book mr-2 text-info"></i>Create/Edit Content</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index"><i class="fas fa-box mr-2 text-info"></i>Categories</a>
        </div>
    </li>
}

else if (!SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" href="#Courses"><i class="fas fa-laptop-code mr-1 text-info"></i>Courses</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#ContactUs"><i class="fas fa-phone-alt mr-1 text-info"></i>Contact Us</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#AboutUs"><i class="fas fa-chalkboard-teacher mr-1 text-info"></i>About Us</a>
    </li>
}

CLOwl_webapp/Views/Shared/_UserRegistrationPartial.cshtml
@model ClowlWebApp.Models.RegistrationModel

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-user mr-2 text-info"></i>Register</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_register">
            </div>
            <form id="UserRegistrationForm" name="UserRegistrationForm" asp-controller="UserAuth" asp-action="RegisterUser">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="RegistrationInValid">
                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Email" placeholder="Email Address" class="form-control">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Password" placeholder="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ConfirmPassword" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="FirstName" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="FirstName" placeholder="First Name" class="form-control">
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="LastName" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="LastName" placeholder="Last Name" class="form-control">
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address1" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address1" placeholder="Address1" class="form-control">
                        <span asp-validation-for="Address1" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address2" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address2" placeholder="Address2" class="form-control">
                        <span asp-validation-for="Address2" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PostCode" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="PostCode" placeholder="Post Code" class="form-control">
                        <span asp-validation-for="PostCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PhoneNumber" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="PhoneNumber" placeholder="Phone Number" class="form-control">
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="form-check">
                            <input asp-for="AcceptUserAgreement" class="form-check-input">
                            <label asp-for="AcceptUserAgreement" class="form-check-label">I accept the <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a></label>
                        </div>
                    </div>
                </div>
                <input type="hidden" asp-for="CategoryId" />
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button id="register" name="register" type="button" class="btn btn-primary">Register</button>
        </div>
    </div>
</div>